fix ins unkown repeat
chrovis/clj-hgvs pull request #10
Opened 2024-09-25 00:26 UTC by nokara26

I fixed ins unknown repeat description.
I referred following format:
- DNA: [insertion](https://hgvs-nomenclature.org/stable/recommendations/DNA/insertion/#examples), [delins](https://hgvs-nomenclature.org/stable/recommendations/DNA/delins/#examples)
- RNA: [insertion](https://hgvs-nomenclature.org/stable/recommendations/RNA/insertion/#examples)
- Protein: [insertion](https://hgvs-nomenclature.org/stable/recommendations/protein/insertion/)

2024-10-11 05:32 UTC, totakke commented
> `g.1134_1135ins(100)` is older hgvs nomenclature?

Yes. You can see it in the following archive site.

> see Uncertain; when the postion and/or the sequence of an inserted sequence has not been defined, a description may have a format like g.(100_150)ins(25)
> https://archive.hgvs-nomenclature.org/recommendations/DNA/variant/insertion/

It got probably deprecated at some point.
I feel like we should add a new repairer (`clj-hgvs.repairer`) from `g.1134_1135ins(100)` to `g.1134_1135insN[100]`.

2024-10-15 00:30 UTC, nokara26 commented
@totakke 
Thank you for reply and review!
I added unknown repeat repairer: https://github.com/chrovis/clj-hgvs/pull/10/commits/ba65e405b1f62523c8c824f06fecaf9ea44fc35f

2024-10-15 05:39 UTC, totakke requested changes
Thank you so much for following the HGVS specification and preparing a repairer to migrate an old expression. 🙇
I have left a couple of comments, and also please bump the version up to `0.5.0-SNAPSHOT`.

2024-10-15 05:39 UTC, totakke commented on src/clj_hgvs/repairer.cljc
> +(defn ^:no-doc replace-unknown-repeated-seq
The description like `insN[100]` does not mean repeated sequences. It expresses an uncertain inserted sequence. I feel like `replace-uncertain-bases` is proper naming.

2024-10-15 05:39 UTC, totakke commented on src/clj_hgvs/mutation.cljc
> +;;;      c.145_147delinsN[10]
Though only a reference page of DNA deletion-insertion have an example of uncertain insertion, theoretically, RNA deletion-insertion and protein deletion-insertion can also have the uncertain insertion. Mutalyzer supports `delinsn`, e.g. https://mutalyzer.nl/normalizer/NM_004006.2:r.2623_2803delinsn. Implementation of the uncertain insertion for only DNA deletion-insertion seems incomplete 🤔

2024-10-16 01:17 UTC, nokara26 commented on src/clj_hgvs/repairer.cljc
> +(defn ^:no-doc replace-unknown-repeated-seq
fix in this commit: https://github.com/chrovis/clj-hgvs/pull/10/commits/b551792360f474ffc6a56421eb44110b9bfcea06

2024-10-16 01:20 UTC, nokara26 commented
@totakke 
Thank you for review!
I fix rna and protein indel and support ins-format: https://github.com/chrovis/clj-hgvs/pull/10/commits/4a0f78802ded0ca8b3b7d19562b633c8aa4664c1
And bump the version up: https://github.com/chrovis/clj-hgvs/pull/10/commits/36d828df711d6e71ecf600853c8d8e35faaa2ab9

2024-10-16 02:34 UTC, totakke approved these changes
Perfection! Thank you so much 👍

2024-10-16 02:52 UTC, federkasten approved these changes
Thank you for your review, @totakke! :pray: 

I have no additional points to add. Thanks!

2024-10-16 02:52 UTC, merged