To correct illegal hgvs strings
chrovis/clj-hgvs pull request #3
Opened 2020-08-28 02:21 UTC by nuggetoriniku

I added two repairer functions to correct illegal hgvs strings.
Could you review this?

2020-08-28 07:40 UTC, totakke requested changes
Thank you for PR. I added some comments. And you should add test cases to [`clj-hgvs.core-test/repair-hgvs-str-test`](https://github.com/chrovis/clj-hgvs/blob/a9203133f219c7fbfc1b0fb0962bc3be520f63bf/test/clj_hgvs/core_test.cljc#L251).

2020-08-28 07:40 UTC, totakke commented on src/clj_hgvs/repairer.cljc
> +  (let [base-pairs {\A \T \T \A \C \G \G \C}
An inversion mutation is not appeared in protein mutations.

```clj
(if (#{:genome :mitochondria :coding-dna :non-coding-dna :circular-dna :rna}
     kind)
  ...
  s)
```

2020-08-28 07:40 UTC, totakke commented on src/clj_hgvs/repairer.cljc
> +(defn ^:no-doc basis->inv
Rename to `substitutions->inv` and add it to above `substitution->delins` in [`built-in-repairers`](https://github.com/chrovis/clj-hgvs/blob/a9203133f219c7fbfc1b0fb0962bc3be520f63bf/src/clj_hgvs/repairer.cljc#L286).

2020-08-28 07:40 UTC, totakke commented on src/clj_hgvs/repairer.cljc
> +      (str "c." region "inv")
The regex does not cover all coordinate patterns. Additionally, I recommend using `replace` fn.

```clj
(letfn [(revcomp [s]
          (->> (reverse s)
               (map {\A \T \T \A \C \G \G \C})
               (apply str)))]
  (string/replace s
                  #"([-\d+*]+_[-\d+*]+)([A-Z]{2,})>([A-Z]{2,})"
                  (fn [[s coords del ins]]
                    (if (= del (revcomp ins))
                      (str coords "inv")
                      s))))
```

2020-08-31 17:11 UTC, nuggetoriniku commented on src/clj_hgvs/repairer.cljc
> +(defn ^:no-doc substitutions->delins*
Thank you for your review.
I removed `substitutions->delins*` function.

2020-08-31 17:15 UTC, nuggetoriniku commented on src/clj_hgvs/repairer.cljc
> +  (let [base-pairs {\A \T \T \A \C \G \G \C}
I set the condition for exclude `:protein`

2020-08-31 17:16 UTC, nuggetoriniku commented on src/clj_hgvs/repairer.cljc
> +(defn ^:no-doc basis->inv
I renamed to `substitutions->inv` and added it in `built-in-repairers`.

2020-08-31 17:20 UTC, nuggetoriniku commented on src/clj_hgvs/repairer.cljc
> +      (str "c." region "inv")
I fixed the regex to cover all coordinate patterns, and changed process with using `replace` fn.

2020-09-01 01:56 UTC, totakke requested changes
Thanks, your fix is perfect, but a test is still missing (https://github.com/chrovis/clj-hgvs/pull/3#pullrequestreview-477303755).

Could you add `c.2210_2211CA>TG` -> `c.2210_2211inv` test case to just above the following line? https://github.com/chrovis/clj-hgvs/blob/a9203133f219c7fbfc1b0fb0962bc3be520f63bf/test/clj_hgvs/core_test.cljc#L286

2020-09-01 07:02 UTC, totakke approved these changes
LGTM. I plan to merge it after @federkasten approval.

2020-09-05 09:34 UTC, federkasten approved these changes
Sorry for the delay in reviewing.
I have checked. No additional comments. Thanks! :+1:

2020-09-05 09:49 UTC, merged